### ISSUE TITLE
N64 Controller Phantom inputs

### ISSUE THREAD

**Issue by lewilou22** [marqs85/gamecon_gpio_rpi#10]
N64 Controller is setup with latest Retropie & this driver.

The N64 Controller is recognized, but most buttons are going on/off a few times a second. 

I have tried a few configuations with the same results 

There is a post about it here with some one having the same issues https://forums.raspberrypi.com/viewtopic.php?t=15787&sid=f29622d54cfa7b21a980cad35416869b&start=475

I have changed the CPU frequencys to preformance 

Any help would be appreciated.

**Comment by marqs85** [comment]
Duplicate of #5.
