### ISSUE TITLE
RPI4 compatibility

### ISSUE THREAD

**Issue by henriz** [marqs85/gamecon_gpio_rpi#3]
This driver does not work on the RPI4, because of the wronge periphal base address.

Changed to this, the driver works again on an RPI4:

`
/*
#ifdef CONFIG_ARCH_MULTI_V7
#define BCM2708_PERI_BASE 0x3F000000
#else
#define BCM2708_PERI_BASE 0x20000000
#endif
*/

#define BCM2708_PERI_BASE 0xFE000000
`

**Comment by marqs85** [comment]
After checking bcm2711_defconfig, CONFIG_BROADCOM_PHY seems to be only defined for BCM2711 in BCM series so perhaps that could be used here to distinquish RPi4's SoC until a more robust solution is made.

**Comment by marqs85** [comment]
Should be fixed by d70ac24

**Comment by henriz** [comment]
This is not the only fix needed. After doing this, the joysticks work fine in jstest, but give a lot of false inputs in retropi.

The fix to this is changing timings.

**Comment by marqs85** [comment]
Is that only with N64/GC pads with their async protocol or other ones as well?

**Comment by henriz** [comment]
I only have PS2 dualshock controllers. Can't say how others would operate. 

I had to change this:

[code]
#define GC_PSX_DELAY	3[/code]

To a delay of 7 to get it to work. Still has some random inputs then, but a lot less. With the 3 value there, you can't even configure the controller in retropie.

The strange thing is that in jstest, the joysticks work flawless. So it might also be an issue with retropie?

I haven't really debugged it, as to me the changing of the delay made it workable enough, but it looks like it's not multitasking correctly. As soon as the joystick-code doesnt get enough CPU time, it picks up half commands or random commands. As with an unloaded CPU it works fine (jstest) but with more load on the CPU (retropi) it starts getting into trouble.

Regarding the dualshocks.. I have them connected using the default wires which are on there, and an 1k8 pullup resistor between data and 3.3v.

**Comment by marqs85** [comment]
Do you have DVFS disabled? The delay (udelay) might be dependant on CPU clock frequency, and PSX controllers operate correctly only at a certain serial clock frequency range (which is generated by the delay).

**Comment by henriz** [comment]
If this is the case, then it might be worth instead of hardcoding this, to get the actual clock speed.

The pi4 is a bit of a bad product, as it has serious heat issues, causing thermal throtteling. Heatsinks alone won't fix this, it needs active cooling.

However, it would be better to get the desired clock frequency in another way. Can't they be hooked up as SPI devices?

**Comment by marqs85** [comment]
It should be possible to use BCM HW SPI controller, but command/data transfers would need to be done byte-by-byte basis with the necessary delay in between generated by SW as there seems to be no way to make the HW insert pauses between bytes.

**Comment by sundaybadboy** [comment]
When I use the PS2 controllers to do the test, the same situation occurs. The clock drift is very serious. Can you use the hardware clock?

**Comment by marqs85** [comment]
By clock drift you mean that in some use case/application the driver works ok while not with another one? Can you try disabling DVFS and see if it helps?

I think the only reliable solution would be utilizing HW SPI controller (there's 1-2 of them available depending on Pi model, both supporting 2 slaves) to communicate with the controllers. That would be best implemented in a dedicated driver since the functionality would be different to gamecon_gpio_rpi (which e.g. allows mixing different controller types and is based on bitbanging).
