### ISSUE TITLE
Do I have to make changes in the codebase for PI zero 2 w?

### ISSUE THREAD

**Issue by ValeriyDP** [marqs85/gamecon_gpio_rpi#9]
I'm trying to figure out  whether I need make changes for that board or not?
The main concern here that this driver was written in time when RPI has 26 pins but now it has a way more and the pins are used for data in current driver are not only data pins.
I've found this repository https://github.com/marqs85/gamecon_gpio_rpi/compare/master...coder-se:gamecon_gpio_rpi:master which was updated not long time ago, but I'm getting error after that command `dkms mkdeb gamecon_gpio_rpi/<VERSION> --source-only`
![image](https://github.com/marqs85/gamecon_gpio_rpi/assets/11663800/caaee64e-0315-4147-97ad-ba035666f1c8)

**Comment by marqs85** [comment]
Not sure if the driver works on PI zero 2 w as-is, but .deb packaging within dkms (dkms mkdeb) seems to be on way of deprecation which might explain why packaging fails. You probably can still build the driver under /usr/src/gamecon_gpio_rpi-1.4 by running make and load in via insmod.

**Comment by marqs85** [comment]
DEB build script has been added in 7771c4f0ecc61340a9a817830c0406564d59f602.
